### ISSUE TITLE
Error when using phantomjs behind SSL certificate

### ISSUE THREAD

**Issue by ricohumme** [Padam87/RasterizeBundle#8]
This is for an update in the documentation:
When working behind a certificate you need some additional parameters for phantomjs.
This worked in my situation. By default PhantomJS sets the ssl-protocol to sslv3

```yaml
padam87_rasterize:
    phantomjs:
        options:
            --ssl-protocol: tlsv1
            --ignore-ssl-errors: true

```
